Repository zainfathoni/kawalmasjid, pull requests merged in 2023-04, with the labels that each got.

#4 FEAT: Show latest 5 places in homepage
  .tool-versions
  app/models/place.server.ts
  app/routes/_index.tsx
  app/routes/places._index.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement, good first issue

#19 feat(address): extract address & mapsUrl into a separate Address model
  prisma/schema.prisma
Labels: enhancement

#24 FEAT: show verified by
  app/models/admin.place.server.ts
  app/routes/admin.places.$placeId._index.tsx
Labels: enhancement, help wanted

#34 Quick fix remove debug component in public and custom icon type
  app/icons/custom.tsx
  app/routes/_auth.login.tsx
  app/routes/_auth.register.tsx
Labels: bug

#36 fix(places): use optional chaining when accessing the first place image
  app/routes/_index.tsx
  app/routes/places.$placeSlug._index.tsx
  app/routes/places._index.tsx
  app/routes/search._index.tsx
Labels: bug, enhancement

#37 Fast forward staging to main
  app/components/ui/button-loading.tsx
  app/components/ui/debug.tsx
  app/root.tsx
  app/routes/admin.tsx
  app/routes/user.places.new._index.tsx
  app/styles/tailwind.css
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  remix.config.js
Labels: enhancement
